name: 'mozdbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mozdbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  mozdbt:
    moz-fx-data-shared-prod:
      +on_schema_change: "append_new_columns"
      +materialized: incremental
      business_models:
        +persist_docs:
          relation: true
          columns: true
        product:
          firefox_desktop:
            +schema: telemetry_derived
          newtab:
            +schema: analysis  # todo: change
