mozdbt:
  outputs:
    dev:
      dataset: tmp
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ env_var('PROJECT_ID', 'moz-fx-data-shared-prod') }}"
      threads: 1
      type: bigquery
  target: dev
